const productList = [
	{ title: "pants", price: 34.55, inventory_count: 4 },
	{ title: "keyboard", price: 46.99, inventory_count: 7 },
	{ title: "lotion", price: 29.65, inventory_count: 9 },
	{ title: "couch", price: 18.66, inventory_count: 0 },
	{ title: "chalk", price: 69.49, inventory_count: 8 },
	{ title: "sofa", price: 25.2, inventory_count: 3 },
	{ title: "piano", price: 74.29, inventory_count: 0 },
	{ title: "nail file", price: 15.27, inventory_count: 0 },
	{ title: "cookie jar", price: 36.5, inventory_count: 5 },
	{ title: "ipod", price: 76.55, inventory_count: 5 },
	{ title: "truck", price: 91.52, inventory_count: 8 },
	{ title: "tooth picks", price: 61.86, inventory_count: 10 },
	{ title: "glasses", price: 34.69, inventory_count: 9 },
	{ title: "fake flowers", price: 99.96, inventory_count: 8 },
	{ title: "sailboat", price: 34.84, inventory_count: 9 },
	{ title: "ice cube tray", price: 98.16, inventory_count: 1 },
	{ title: "watch", price: 65.86, inventory_count: 1 },
	{ title: "apple", price: 63.5, inventory_count: 9 },
	{ title: "sponge", price: 81.93, inventory_count: 2 },
	{ title: "shoes", price: 47.7, inventory_count: 0 },
	{ title: "bananas", price: 9.84, inventory_count: 7 },
	{ title: "bottle cap", price: 91.26, inventory_count: 2 },
	{ title: "helmet", price: 61.9, inventory_count: 2 },
	{ title: "video games", price: 66.0, inventory_count: 0 },
	{ title: "tv", price: 68.44, inventory_count: 0 },
	{ title: "rubber duck", price: 40.48, inventory_count: 4 },
	{ title: "hair brush", price: 94.73, inventory_count: 9 },
	{ title: "bread", price: 17.39, inventory_count: 1 },
	{ title: "soap", price: 88.48, inventory_count: 5 },
	{ title: "brocolli", price: 70.01, inventory_count: 4 },
	{ title: "flag", price: 77.96, inventory_count: 4 },
	{ title: "bow", price: 10.73, inventory_count: 11 },
	{ title: "milk", price: 43.17, inventory_count: 6 },
	{ title: "mouse pad", price: 52.37, inventory_count: 8 },
	{ title: "computer", price: 18.47, inventory_count: 7 },
	{ title: "toe ring", price: 50.22, inventory_count: 0 },
	{ title: "puddle", price: 31.14, inventory_count: 3 },
	{ title: "tree", price: 88.7, inventory_count: 9 },
	{ title: "canvas", price: 66.37, inventory_count: 6 },
	{ title: "twister", price: 82.49, inventory_count: 11 },
	{ title: "pen", price: 28.73, inventory_count: 7 },
	{ title: "cinder block", price: 92.41, inventory_count: 10 },
	{ title: "shoe lace", price: 54.86, inventory_count: 11 },
	{ title: "door", price: 14.86, inventory_count: 5 },
	{ title: "sandal", price: 90.93, inventory_count: 8 },
	{ title: "white out", price: 93.91, inventory_count: 8 },
	{ title: "toothbrush", price: 43.19, inventory_count: 2 },
	{ title: "socks", price: 10.93, inventory_count: 0 },
	{ title: "perfume", price: 47.37, inventory_count: 1 },
	{ title: "car", price: 33.18, inventory_count: 11 },
	{ title: "chapter book", price: 63.6, inventory_count: 0 },
	{ title: "paper", price: 85.91, inventory_count: 1 },
	{ title: "speakers", price: 19.93, inventory_count: 11 },
	{ title: "box", price: 2.87, inventory_count: 1 },
	{ title: "remote", price: 90.22, inventory_count: 2 },
	{ title: "nail clippers", price: 91.38, inventory_count: 9 },
	{ title: "greeting card", price: 82.67, inventory_count: 0 },
	{ title: "fridge", price: 85.12, inventory_count: 0 },
	{ title: "grid paper", price: 55.01, inventory_count: 6 },
	{ title: "keys", price: 85.32, inventory_count: 6 },
	{ title: "balloon", price: 4.57, inventory_count: 11 },
	{ title: "toilet", price: 79.93, inventory_count: 7 },
	{ title: "monitor", price: 28.47, inventory_count: 0 },
	{ title: "spoon", price: 57.44, inventory_count: 8 },
	{ title: "mp3 player", price: 57.72, inventory_count: 0 },
	{ title: "outlet", price: 38.04, inventory_count: 7 },
	{ title: "clock", price: 61.96, inventory_count: 11 },
	{ title: "newspaper", price: 70.97, inventory_count: 11 },
	{ title: "glass", price: 95.75, inventory_count: 8 },
	{ title: "eye liner", price: 98.68, inventory_count: 1 },
	{ title: "eraser", price: 14.63, inventory_count: 7 },
	{ title: "soy sauce packet", price: 19.52, inventory_count: 6 },
	{ title: "spring", price: 83.25, inventory_count: 6 },
	{ title: "credit card", price: 92.67, inventory_count: 3 },
	{ title: "stop sign", price: 44.14, inventory_count: 0 },
	{ title: "face wash", price: 98.67, inventory_count: 11 },
	{ title: "bookmark", price: 79.93, inventory_count: 9 },
	{ title: "radio", price: 26.1, inventory_count: 0 },
	{ title: "candle", price: 49.23, inventory_count: 4 },
	{ title: "lip gloss", price: 38.65, inventory_count: 6 },
	{ title: "needle", price: 84.51, inventory_count: 0 },
	{ title: "television", price: 64.65, inventory_count: 8 },
	{ title: "plastic fork", price: 80.47, inventory_count: 0 },
	{ title: "clamp", price: 4.03, inventory_count: 10 },
	{ title: "model car", price: 5.9, inventory_count: 7 },
	{ title: "tomato", price: 74.2, inventory_count: 1 },
	{ title: "phone", price: 87.24, inventory_count: 9 },
	{ title: "beef", price: 57.04, inventory_count: 9 },
	{ title: "sticky note", price: 67.66, inventory_count: 11 },
	{ title: "stockings", price: 81.27, inventory_count: 2 },
	{ title: "blanket", price: 54.81, inventory_count: 3 },
	{ title: "thermostat", price: 4.76, inventory_count: 0 },
	{ title: "purse", price: 72.17, inventory_count: 1 },
	{ title: "button", price: 34.82, inventory_count: 0 },
	{ title: "sand paper", price: 68.44, inventory_count: 0 },
	{ title: "screw", price: 4.06, inventory_count: 11 },
	{ title: "house", price: 31.3, inventory_count: 5 },
	{ title: "bottle", price: 73.66, inventory_count: 4 },
	{ title: "glow stick", price: 31.97, inventory_count: 0 },
	{ title: "chair", price: 79.41, inventory_count: 0 },
];

module.exports = {
	productList
}