const productList = [
	{ title: "pants", price: 21.08, inventory_count: 7 },
	{ title: "keyboard", price: 19.03, inventory_count: 4 },
	{ title: "lotion", price: 8.65, inventory_count: 5 },
	{ title: "couch", price: 97.43, inventory_count: 5 },
	{ title: "chalk", price: 43.0, inventory_count: 1 },
	{ title: "sofa", price: 25.73, inventory_count: 7 },
	{ title: "piano", price: 86.76, inventory_count: 0 },
	{ title: "nail file", price: 98.57, inventory_count: 6 },
	{ title: "cookie jar", price: 81.36, inventory_count: 7 },
	{ title: "ipod", price: 90.58, inventory_count: 7 },
	{ title: "truck", price: 3.84, inventory_count: 3 },
	{ title: "tooth picks", price: 59.46, inventory_count: 0 },
	{ title: "glasses", price: 100.33, inventory_count: 0 },
	{ title: "fake flowers", price: 90.62, inventory_count: 8 },
	{ title: "sailboat", price: 10.74, inventory_count: 0 },
	{ title: "ice cube tray", price: 43.15, inventory_count: 3 },
	{ title: "watch", price: 13.47, inventory_count: 10 },
	{ title: "apple", price: 52.68, inventory_count: 0 },
	{ title: "sponge", price: 87.49, inventory_count: 1 },
	{ title: "shoes", price: 34.86, inventory_count: 4 },
	{ title: "bananas", price: 98.39, inventory_count: 0 },
	{ title: "bottle cap", price: 52.11, inventory_count: 9 },
	{ title: "helmet", price: 45.52, inventory_count: 10 },
	{ title: "video games", price: 55.66, inventory_count: 3 },
	{ title: "tv", price: 40.57, inventory_count: 1 },
	{ title: "rubber duck", price: 65.34, inventory_count: 3 },
	{ title: "hair brush", price: 70.74, inventory_count: 3 },
	{ title: "bread", price: 63.62, inventory_count: 5 },
	{ title: "soap", price: 93.8, inventory_count: 3 },
	{ title: "brocolli", price: 57.85, inventory_count: 0 },
	{ title: "flag", price: 59.68, inventory_count: 9 },
	{ title: "bow", price: 3.48, inventory_count: 8 },
	{ title: "milk", price: 61.7, inventory_count: 0 },
	{ title: "mouse pad", price: 80.3, inventory_count: 0 },
	{ title: "computer", price: 32.06, inventory_count: 5 },
	{ title: "toe ring", price: 64.88, inventory_count: 0 },
	{ title: "puddle", price: 26.24, inventory_count: 4 },
	{ title: "tree", price: 100.69, inventory_count: 9 },
	{ title: "canvas", price: 98.95, inventory_count: 2 },
	{ title: "twister", price: 35.39, inventory_count: 0 },
	{ title: "pen", price: 91.66, inventory_count: 9 },
	{ title: "cinder block", price: 13.66, inventory_count: 6 },
	{ title: "shoe lace", price: 69.16, inventory_count: 0 },
	{ title: "door", price: 7.01, inventory_count: 0 },
	{ title: "sandal", price: 26.72, inventory_count: 0 },
	{ title: "white out", price: 17.73, inventory_count: 3 },
	{ title: "toothbrush", price: 76.25, inventory_count: 3 },
	{ title: "socks", price: 82.55, inventory_count: 5 },
	{ title: "perfume", price: 14.03, inventory_count: 4 },
	{ title: "car", price: 36.44, inventory_count: 0 },
	{ title: "chapter book", price: 70.73, inventory_count: 4 },
	{ title: "paper", price: 20.55, inventory_count: 6 },
	{ title: "speakers", price: 80.76, inventory_count: 0 },
	{ title: "box", price: 79.11, inventory_count: 6 },
	{ title: "remote", price: 96.34, inventory_count: 0 },
	{ title: "nail clippers", price: 76.07, inventory_count: 0 },
	{ title: "greeting card", price: 12.82, inventory_count: 0 },
	{ title: "fridge", price: 4.15, inventory_count: 0 },
	{ title: "grid paper", price: 18.58, inventory_count: 6 },
	{ title: "keys", price: 25.3, inventory_count: 11 },
	{ title: "balloon", price: 40.04, inventory_count: 0 },
	{ title: "toilet", price: 4.67, inventory_count: 6 },
	{ title: "monitor", price: 62.52, inventory_count: 4 },
	{ title: "spoon", price: 84.79, inventory_count: 2 },
	{ title: "mp3 player", price: 91.54, inventory_count: 7 },
	{ title: "outlet", price: 17.21, inventory_count: 7 },
	{ title: "clock", price: 67.82, inventory_count: 10 },
	{ title: "newspaper", price: 3.99, inventory_count: 2 },
	{ title: "glass", price: 89.59, inventory_count: 7 },
	{ title: "eye liner", price: 14.66, inventory_count: 10 },
	{ title: "eraser", price: 4.59, inventory_count: 10 },
	{ title: "soy sauce packet", price: 86.15, inventory_count: 6 },
	{ title: "spring", price: 100.58, inventory_count: 1 },
	{ title: "credit card", price: 73.52, inventory_count: 6 },
	{ title: "stop sign", price: 14.68, inventory_count: 8 },
	{ title: "face wash", price: 66.05, inventory_count: 9 },
	{ title: "bookmark", price: 39.24, inventory_count: 6 },
	{ title: "radio", price: 21.11, inventory_count: 2 },
	{ title: "candle", price: 93.97, inventory_count: 6 },
	{ title: "lip gloss", price: 24.65, inventory_count: 7 },
	{ title: "needle", price: 30.3, inventory_count: 0 },
	{ title: "television", price: 83.59, inventory_count: 7 },
	{ title: "plastic fork", price: 2.82, inventory_count: 11 },
	{ title: "clamp", price: 72.92, inventory_count: 4 },
	{ title: "model car", price: 59.11, inventory_count: 2 },
	{ title: "tomato", price: 1.99, inventory_count: 1 },
	{ title: "phone", price: 96.09, inventory_count: 0 },
	{ title: "beef", price: 81.49, inventory_count: 5 },
	{ title: "sticky note", price: 20.0, inventory_count: 6 },
	{ title: "stockings", price: 54.77, inventory_count: 8 },
	{ title: "blanket", price: 3.88, inventory_count: 0 },
	{ title: "thermostat", price: 65.55, inventory_count: 3 },
	{ title: "purse", price: 5.73, inventory_count: 10 },
	{ title: "button", price: 60.58, inventory_count: 11 },
	{ title: "sand paper", price: 89.11, inventory_count: 11 },
	{ title: "screw", price: 45.31, inventory_count: 8 },
	{ title: "house", price: 72.4, inventory_count: 4 },
	{ title: "bottle", price: 99.48, inventory_count: 0 },
	{ title: "glow stick", price: 99.97, inventory_count: 3 },
	{ title: "chair", price: 1.97, inventory_count: 9 },
];

module.exports = {
	productList
}